package mif.vu.sarunas.labwork.mybatis.model;

public class RecipeIngredient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RECIPE_INGREDIENT.RECIPES_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    private Long recipesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RECIPE_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    private Long ingredientsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RECIPE_INGREDIENT.RECIPES_ID
     *
     * @return the value of PUBLIC.RECIPE_INGREDIENT.RECIPES_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public Long getRecipesId() {
        return recipesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RECIPE_INGREDIENT.RECIPES_ID
     *
     * @param recipesId the value for PUBLIC.RECIPE_INGREDIENT.RECIPES_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public void setRecipesId(Long recipesId) {
        this.recipesId = recipesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RECIPE_INGREDIENT.INGREDIENTS_ID
     *
     * @return the value of PUBLIC.RECIPE_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public Long getIngredientsId() {
        return ingredientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RECIPE_INGREDIENT.INGREDIENTS_ID
     *
     * @param ingredientsId the value for PUBLIC.RECIPE_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public void setIngredientsId(Long ingredientsId) {
        this.ingredientsId = ingredientsId;
    }
}