package mif.vu.sarunas.labwork.mybatis.model;

import java.util.Date;

public class Recipe {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.ID
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.CREATION_DATE
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private Date creationDate = new Date();

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.DESCRIPTION
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.INSTRUCTIONS
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private String instructions;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.NAME
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column PUBLIC.RECIPE.TAG_ID
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	private Long tagId;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.ID
	 *
	 * @return the value of PUBLIC.RECIPE.ID
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.ID
	 *
	 * @param id the value for PUBLIC.RECIPE.ID
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.CREATION_DATE
	 *
	 * @return the value of PUBLIC.RECIPE.CREATION_DATE
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.CREATION_DATE
	 *
	 * @param creationDate the value for PUBLIC.RECIPE.CREATION_DATE
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.DESCRIPTION
	 *
	 * @return the value of PUBLIC.RECIPE.DESCRIPTION
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.DESCRIPTION
	 *
	 * @param description the value for PUBLIC.RECIPE.DESCRIPTION
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.INSTRUCTIONS
	 *
	 * @return the value of PUBLIC.RECIPE.INSTRUCTIONS
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public String getInstructions() {
		return instructions;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.INSTRUCTIONS
	 *
	 * @param instructions the value for PUBLIC.RECIPE.INSTRUCTIONS
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.NAME
	 *
	 * @return the value of PUBLIC.RECIPE.NAME
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.NAME
	 *
	 * @param name the value for PUBLIC.RECIPE.NAME
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column PUBLIC.RECIPE.TAG_ID
	 *
	 * @return the value of PUBLIC.RECIPE.TAG_ID
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public Long getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column PUBLIC.RECIPE.TAG_ID
	 *
	 * @param tagId the value for PUBLIC.RECIPE.TAG_ID
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}
}