package mif.vu.sarunas.labwork.mybatis.model;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TAG.ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TAG.NAME
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TAG.ID
     *
     * @return the value of PUBLIC.TAG.ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TAG.ID
     *
     * @param id the value for PUBLIC.TAG.ID
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TAG.NAME
     *
     * @return the value of PUBLIC.TAG.NAME
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TAG.NAME
     *
     * @param name the value for PUBLIC.TAG.NAME
     *
     * @mbg.generated Sun Mar 17 23:42:02 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}