package mif.vu.sarunas.labwork.mybatis.dao;

import mif.vu.sarunas.labwork.mybatis.model.Ingredient;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface IngredientMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table PUBLIC.INGREDIENT
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table PUBLIC.INGREDIENT
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	int insert(Ingredient record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table PUBLIC.INGREDIENT
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	Ingredient selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table PUBLIC.INGREDIENT
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	List<Ingredient> selectAll();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table PUBLIC.INGREDIENT
	 *
	 * @mbg.generated Sun Mar 17 23:42:02 EET 2024
	 */
	int updateByPrimaryKey(Ingredient record);
}